// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mintmark.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace Mintmark.Infrastructure.Persistence.Migrations;
[DbContext(typeof(MintmarkDbContext))]
partial class MintmarkDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "10.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
        NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<long>", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text")
                    .HasColumnName("concurrency_stamp");

                b.Property<string>("Name")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("name");

                b.Property<string>("NormalizedName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_name");

                b.HasKey("Id")
                    .HasName("pk_asp_net_roles");

                b.HasIndex("NormalizedName")
                    .IsUnique()
                    .HasDatabaseName("role_name_index");

                b.ToTable("asp_net_roles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text")
                    .HasColumnName("claim_value");

                b.Property<long>("RoleId")
                    .HasColumnType("bigint")
                    .HasColumnName("role_id");

                b.HasKey("Id")
                    .HasName("pk_asp_net_role_claims");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_asp_net_role_claims_role_id");

                b.ToTable("asp_net_role_claims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("ClaimType")
                    .HasColumnType("text")
                    .HasColumnName("claim_type");

                b.Property<string>("ClaimValue")
                    .HasColumnType("text")
                    .HasColumnName("claim_value");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_asp_net_user_claims");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_asp_net_user_claims_user_id");

                b.ToTable("asp_net_user_claims", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
            {
                b.Property<string>("LoginProvider")
                    .HasColumnType("text")
                    .HasColumnName("login_provider");

                b.Property<string>("ProviderKey")
                    .HasColumnType("text")
                    .HasColumnName("provider_key");

                b.Property<string>("ProviderDisplayName")
                    .HasColumnType("text")
                    .HasColumnName("provider_display_name");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.HasKey("LoginProvider", "ProviderKey")
                    .HasName("pk_asp_net_user_logins");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_asp_net_user_logins_user_id");

                b.ToTable("asp_net_user_logins", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
            {
                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.Property<long>("RoleId")
                    .HasColumnType("bigint")
                    .HasColumnName("role_id");

                b.HasKey("UserId", "RoleId")
                    .HasName("pk_asp_net_user_roles");

                b.HasIndex("RoleId")
                    .HasDatabaseName("ix_asp_net_user_roles_role_id");

                b.ToTable("asp_net_user_roles", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
            {
                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.Property<string>("LoginProvider")
                    .HasColumnType("text")
                    .HasColumnName("login_provider");

                b.Property<string>("Name")
                    .HasColumnType("text")
                    .HasColumnName("name");

                b.Property<string>("Value")
                    .HasColumnType("text")
                    .HasColumnName("value");

                b.HasKey("UserId", "LoginProvider", "Name")
                    .HasName("pk_asp_net_user_tokens");

                b.ToTable("asp_net_user_tokens", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.CoinImage", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTimeOffset?>("CapturedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("captured_at_utc");

                b.Property<string>("ContentType")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("content_type");

                b.Property<long>("HoldingId")
                    .HasColumnType("bigint")
                    .HasColumnName("holding_id");

                b.Property<string>("Notes")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("notes");

                b.Property<long>("PerceptualHash")
                    .HasColumnType("bigint")
                    .HasColumnName("perceptual_hash");

                b.Property<string>("Side")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("side");

                b.Property<string>("StorageKey")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("storage_key");

                b.HasKey("Id")
                    .HasName("pk_coin_images");

                b.HasIndex("HoldingId")
                    .HasDatabaseName("ix_coin_images_holding_id");

                b.ToTable("coin_images", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.CoinType", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<decimal>("ActualMetalWeightTroyOz")
                    .HasColumnType("numeric(18,6)")
                    .HasColumnName("actual_metal_weight_troy_oz");

                b.Property<decimal?>("DiameterMillimeters")
                    .HasColumnType("numeric(8,3)")
                    .HasColumnName("diameter_millimeters");

                b.Property<string>("Edge")
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("edge");

                b.Property<decimal>("Fineness")
                    .HasColumnType("numeric(6,4)")
                    .HasColumnName("fineness");

                b.Property<string>("Finish")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("finish");

                b.Property<int>("FinishAttributes")
                    .HasColumnType("integer")
                    .HasColumnName("finish_attributes");

                b.Property<decimal>("GrossWeightGrams")
                    .HasColumnType("numeric(18,6)")
                    .HasColumnName("gross_weight_grams");

                b.Property<string>("KmNumber")
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("km_number");

                b.Property<long>("MintId")
                    .HasColumnType("bigint")
                    .HasColumnName("mint_id");

                b.Property<long?>("Mintage")
                    .HasColumnType("bigint")
                    .HasColumnName("mintage");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)")
                    .HasColumnName("name");

                b.Property<string>("ObverseImageKey")
                    .HasColumnType("text")
                    .HasColumnName("obverse_image_key");

                b.Property<string>("RedBookReference")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("red_book_reference");

                b.Property<string>("ReverseImageKey")
                    .HasColumnType("text")
                    .HasColumnName("reverse_image_key");

                b.Property<long>("SeriesId")
                    .HasColumnType("bigint")
                    .HasColumnName("series_id");

                b.Property<string>("SourceUrl")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("source_url");

                b.Property<decimal?>("ThicknessMillimeters")
                    .HasColumnType("numeric(8,3)")
                    .HasColumnName("thickness_millimeters");

                b.Property<int>("Year")
                    .HasColumnType("integer")
                    .HasColumnName("year");

                b.HasKey("Id")
                    .HasName("pk_coin_types");

                b.HasIndex("MintId")
                    .HasDatabaseName("ix_coin_types_mint_id");

                b.HasIndex("Name")
                    .HasDatabaseName("ix_coin_types_name");

                NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Name"), "gin");
                NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Name"), new[] { "gin_trgm_ops" });

                b.HasIndex("SeriesId", "Year")
                    .HasDatabaseName("ix_coin_types_series_id_year");

                b.ToTable("coin_types", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Grading", b =>
            {
                b.Property<long>("HoldingId")
                    .HasColumnType("bigint")
                    .HasColumnName("holding_id");

                b.Property<string>("CertificationNumber")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("certification_number");

                b.Property<int>("Designations")
                    .HasColumnType("integer")
                    .HasColumnName("designations");

                b.Property<string>("LabelPedigree")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("label_pedigree");

                b.Property<int?>("NumericGrade")
                    .HasColumnType("integer")
                    .HasColumnName("numeric_grade");

                b.Property<string>("Service")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("service");

                b.Property<string>("VerificationUrl")
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("verification_url");

                b.HasKey("HoldingId")
                    .HasName("pk_gradings");

                b.ToTable("gradings", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Holding", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<long?>("CoinTypeId")
                    .HasColumnType("bigint")
                    .HasColumnName("coin_type_id");

                b.Property<string>("Dealer")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("dealer");

                b.Property<string>("Form")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("form");

                b.Property<bool>("IsDeleted")
                    .HasColumnType("boolean")
                    .HasColumnName("is_deleted");

                b.Property<string>("Notes")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)")
                    .HasColumnName("notes");

                b.Property<string>("PackagingState")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("packaging_state");

                b.Property<DateTimeOffset>("PurchasedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("purchased_at_utc");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<string>("SerialNumber")
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("serial_number");

                b.Property<string>("StorageLocation")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("storage_location");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.ComplexProperty(typeof(Dictionary<string, object>), "PurchasePricePerUnit", "Mintmark.Domain.Entities.Holding.PurchasePricePerUnit#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasColumnType("numeric(18,4)")
                            .HasColumnName("purchase_price_per_unit_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("char(3)")
                            .HasColumnName("purchase_price_per_unit_currency");
                    });

                b.HasKey("Id")
                    .HasName("pk_holdings");

                b.HasIndex("CoinTypeId")
                    .HasDatabaseName("ix_holdings_coin_type_id");

                b.HasIndex("UserId", "IsDeleted")
                    .HasDatabaseName("ix_holdings_user_id_is_deleted");

                b.ToTable("holdings", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.HoldingRevision", b =>
            {
                b.Property<long>("HoldingId")
                    .HasColumnType("bigint")
                    .HasColumnName("holding_id");

                b.Property<int>("RevisionNumber")
                    .HasColumnType("integer")
                    .HasColumnName("revision_number");

                b.Property<int>("Quantity")
                    .HasColumnType("integer")
                    .HasColumnName("quantity");

                b.Property<string>("Reason")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)")
                    .HasColumnName("reason");

                b.Property<DateTimeOffset>("RevisedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("revised_at_utc");

                b.ComplexProperty(typeof(Dictionary<string, object>), "PurchasePricePerUnit", "Mintmark.Domain.Entities.HoldingRevision.PurchasePricePerUnit#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasColumnType("numeric(18,4)")
                            .HasColumnName("purchase_price_per_unit_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("char(3)")
                            .HasColumnName("purchase_price_per_unit_currency");
                    });

                b.HasKey("HoldingId", "RevisionNumber")
                    .HasName("pk_holding_revisions");

                b.ToTable("holding_revisions", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.IdentificationRun", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("Candidates")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("candidates");

                b.Property<DateTimeOffset?>("ConfirmedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("confirmed_at_utc");

                b.Property<string>("ConfirmedBy")
                    .HasColumnType("text")
                    .HasColumnName("confirmed_by");

                b.Property<long?>("ConfirmedCoinTypeId")
                    .HasColumnType("bigint")
                    .HasColumnName("confirmed_coin_type_id");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<long?>("EdgeImageId")
                    .HasColumnType("bigint")
                    .HasColumnName("edge_image_id");

                b.Property<string>("FieldConfidences")
                    .IsRequired()
                    .HasColumnType("jsonb")
                    .HasColumnName("field_confidences");

                b.Property<string>("ModelName")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("model_name");

                b.Property<string>("ModelVersion")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("model_version");

                b.Property<long?>("ObverseImageId")
                    .HasColumnType("bigint")
                    .HasColumnName("obverse_image_id");

                b.Property<long?>("ObversePerceptualHash")
                    .HasColumnType("bigint")
                    .HasColumnName("obverse_perceptual_hash");

                b.Property<string>("PromptTemplateVersion")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)")
                    .HasColumnName("prompt_template_version");

                b.Property<string>("RawResponse")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("raw_response");

                b.Property<long?>("ReverseImageId")
                    .HasColumnType("bigint")
                    .HasColumnName("reverse_image_id");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_identification_runs");

                b.HasIndex("ObversePerceptualHash")
                    .HasDatabaseName("ix_identification_runs_obverse_perceptual_hash");

                b.HasIndex("UserId")
                    .HasDatabaseName("ix_identification_runs_user_id");

                b.ToTable("identification_runs", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Mint", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("Country")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)")
                    .HasColumnName("country");

                b.Property<string>("CountryCode")
                    .IsRequired()
                    .HasMaxLength(2)
                    .HasColumnType("character varying(2)")
                    .HasColumnName("country_code");

                b.Property<int?>("FoundedYear")
                    .HasColumnType("integer")
                    .HasColumnName("founded_year");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean")
                    .HasColumnName("is_active");

                b.Property<string>("LogoAssetKey")
                    .HasColumnType("text")
                    .HasColumnName("logo_asset_key");

                b.PrimitiveCollection<string[]>("MintMarks")
                    .IsRequired()
                    .HasColumnType("text[]")
                    .HasColumnName("mint_marks");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.Property<string>("Notes")
                    .HasColumnType("text")
                    .HasColumnName("notes");

                b.HasKey("Id")
                    .HasName("pk_mints");

                b.HasIndex("Name")
                    .HasDatabaseName("ix_mints_name");

                b.ToTable("mints", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Series", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<int?>("EndYear")
                    .HasColumnType("integer")
                    .HasColumnName("end_year");

                b.Property<string>("Metal")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("metal");

                b.Property<long>("MintId")
                    .HasColumnType("bigint")
                    .HasColumnName("mint_id");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("name");

                b.Property<string>("Notes")
                    .HasColumnType("text")
                    .HasColumnName("notes");

                b.Property<int?>("StartYear")
                    .HasColumnType("integer")
                    .HasColumnName("start_year");

                b.HasKey("Id")
                    .HasName("pk_series");

                b.HasIndex("MintId")
                    .HasDatabaseName("ix_series_mint_id");

                b.HasIndex("Name")
                    .HasDatabaseName("ix_series_name");

                b.ToTable("series", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.SpotPrice", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<string>("Currency")
                    .IsRequired()
                    .HasColumnType("char(3)")
                    .HasColumnName("currency");

                b.Property<DateTimeOffset>("IngestedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("ingested_at_utc");

                b.Property<string>("Metal")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("metal");

                b.Property<string>("ProviderName")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("provider_name");

                b.Property<DateTimeOffset>("SourceTimestampUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("source_timestamp_utc");

                b.ComplexProperty(typeof(Dictionary<string, object>), "AskPerTroyOunce", "Mintmark.Domain.Entities.SpotPrice.AskPerTroyOunce#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasColumnType("numeric(18,4)")
                            .HasColumnName("ask_per_troy_ounce_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("char(3)")
                            .HasColumnName("ask_per_troy_ounce_currency");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "BidPerTroyOunce", "Mintmark.Domain.Entities.SpotPrice.BidPerTroyOunce#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasColumnType("numeric(18,4)")
                            .HasColumnName("bid_per_troy_ounce_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("char(3)")
                            .HasColumnName("bid_per_troy_ounce_currency");
                    });

                b.ComplexProperty(typeof(Dictionary<string, object>), "PricePerTroyOunce", "Mintmark.Domain.Entities.SpotPrice.PricePerTroyOunce#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasColumnType("numeric(18,4)")
                            .HasColumnName("price_per_troy_ounce_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("char(3)")
                            .HasColumnName("price_per_troy_ounce_currency");
                    });

                b.HasKey("Id")
                    .HasName("pk_spot_prices");

                b.HasIndex("Metal", "Currency", "SourceTimestampUtc")
                    .IsDescending(false, false, true)
                    .HasDatabaseName("ix_spot_prices_metal_currency_source_timestamp_utc");

                b.ToTable("spot_prices", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.SpotPriceDaily", b =>
            {
                b.Property<string>("Metal")
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("metal");

                b.Property<string>("Currency")
                    .HasColumnType("char(3)")
                    .HasColumnName("currency");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date")
                    .HasColumnName("date");

                b.Property<DateTimeOffset>("IngestedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("ingested_at_utc");

                b.Property<string>("ProviderName")
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("provider_name");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Close", "Mintmark.Domain.Entities.SpotPriceDaily.Close#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasColumnType("numeric(18,4)")
                            .HasColumnName("close_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("char(3)")
                            .HasColumnName("close_currency");
                    });

                b.HasKey("Metal", "Currency", "Date")
                    .HasName("pk_spot_price_daily");

                b.ToTable("spot_price_daily", (string)null);
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Valuation", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTimeOffset>("ComputedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("computed_at_utc");

                b.Property<decimal>("ConfidenceBandHigh")
                    .HasColumnType("numeric(6,4)")
                    .HasColumnName("confidence_band_high");

                b.Property<decimal>("ConfidenceBandLow")
                    .HasColumnType("numeric(6,4)")
                    .HasColumnName("confidence_band_low");

                b.Property<long?>("DerivedFromSpotPriceId")
                    .HasColumnType("bigint")
                    .HasColumnName("derived_from_spot_price_id");

                b.Property<long>("HoldingId")
                    .HasColumnType("bigint")
                    .HasColumnName("holding_id");

                b.Property<string>("Method")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("method");

                b.Property<string>("MethodVersion")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)")
                    .HasColumnName("method_version");

                b.Property<string>("SpotProviderName")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("spot_provider_name");

                b.Property<DateTimeOffset>("SpotSourceTimestampUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("spot_source_timestamp_utc");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("type");

                b.ComplexProperty(typeof(Dictionary<string, object>), "Value", "Mintmark.Domain.Entities.Valuation.Value#Money", b1 =>
                    {
                        b1.IsRequired();

                        b1.Property<decimal>("Amount")
                            .HasColumnType("numeric(18,4)")
                            .HasColumnName("value_amount");

                        b1.Property<string>("Currency")
                            .IsRequired()
                            .HasColumnType("char(3)")
                            .HasColumnName("value_currency");
                    });

                b.HasKey("Id")
                    .HasName("pk_valuations");

                b.HasIndex("DerivedFromSpotPriceId")
                    .HasDatabaseName("ix_valuations_derived_from_spot_price_id");

                b.HasIndex("HoldingId", "ComputedAtUtc")
                    .HasDatabaseName("ix_valuations_holding_id_computed_at_utc");

                b.ToTable("valuations", (string)null);
            });

        modelBuilder.Entity("Mintmark.Infrastructure.Persistence.IdempotencyRecord", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<string>("Endpoint")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("endpoint");

                b.Property<string>("IdempotencyKey")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)")
                    .HasColumnName("idempotency_key");

                b.Property<string>("ResponseBody")
                    .IsRequired()
                    .HasColumnType("text")
                    .HasColumnName("response_body");

                b.Property<int>("StatusCode")
                    .HasColumnType("integer")
                    .HasColumnName("status_code");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_idempotency_records");

                b.HasIndex("UserId", "IdempotencyKey")
                    .IsUnique()
                    .HasDatabaseName("ix_idempotency_records_user_id_idempotency_key");

                b.ToTable("idempotency_records", (string)null);
            });

        modelBuilder.Entity("Mintmark.Infrastructure.Persistence.MintmarkUser", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<int>("AccessFailedCount")
                    .HasColumnType("integer")
                    .HasColumnName("access_failed_count");

                b.Property<string>("ConcurrencyStamp")
                    .IsConcurrencyToken()
                    .HasColumnType("text")
                    .HasColumnName("concurrency_stamp");

                b.Property<string>("DisplayName")
                    .HasColumnType("text")
                    .HasColumnName("display_name");

                b.Property<string>("Email")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("email");

                b.Property<bool>("EmailConfirmed")
                    .HasColumnType("boolean")
                    .HasColumnName("email_confirmed");

                b.Property<bool>("LockoutEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("lockout_enabled");

                b.Property<DateTimeOffset?>("LockoutEnd")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("lockout_end");

                b.Property<string>("NormalizedEmail")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_email");

                b.Property<string>("NormalizedUserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("normalized_user_name");

                b.Property<string>("PasswordHash")
                    .HasColumnType("text")
                    .HasColumnName("password_hash");

                b.Property<string>("PhoneNumber")
                    .HasColumnType("text")
                    .HasColumnName("phone_number");

                b.Property<bool>("PhoneNumberConfirmed")
                    .HasColumnType("boolean")
                    .HasColumnName("phone_number_confirmed");

                b.Property<string>("SecurityStamp")
                    .HasColumnType("text")
                    .HasColumnName("security_stamp");

                b.Property<bool>("TwoFactorEnabled")
                    .HasColumnType("boolean")
                    .HasColumnName("two_factor_enabled");

                b.Property<string>("UserName")
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)")
                    .HasColumnName("user_name");

                b.HasKey("Id")
                    .HasName("pk_asp_net_users");

                b.HasIndex("NormalizedEmail")
                    .HasDatabaseName("email_index");

                b.HasIndex("NormalizedUserName")
                    .IsUnique()
                    .HasDatabaseName("user_name_index");

                b.ToTable("asp_net_users", (string)null);
            });

        modelBuilder.Entity("Mintmark.Infrastructure.Persistence.ReferenceImage", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<long>("CoinTypeId")
                    .HasColumnType("bigint")
                    .HasColumnName("coin_type_id");

                b.Property<Vector>("Embedding")
                    .HasColumnType("vector(768)")
                    .HasColumnName("embedding");

                b.Property<long>("PerceptualHash")
                    .HasColumnType("bigint")
                    .HasColumnName("perceptual_hash");

                b.Property<string>("Side")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)")
                    .HasColumnName("side");

                b.Property<string>("StorageKey")
                    .IsRequired()
                    .HasMaxLength(300)
                    .HasColumnType("character varying(300)")
                    .HasColumnName("storage_key");

                b.HasKey("Id")
                    .HasName("pk_reference_images");

                b.HasIndex("CoinTypeId")
                    .HasDatabaseName("ix_reference_images_coin_type_id");

                b.HasIndex("Embedding")
                    .HasDatabaseName("ix_reference_images_embedding");

                NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Embedding"), "hnsw");
                NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("Embedding"), new[] { "vector_cosine_ops" });

                b.ToTable("reference_images", (string)null);
            });

        modelBuilder.Entity("Mintmark.Infrastructure.Persistence.RefreshToken", b =>
            {
                b.Property<long>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("bigint")
                    .HasColumnName("id");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                b.Property<DateTimeOffset?>("ConsumedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("consumed_at_utc");

                b.Property<DateTimeOffset>("CreatedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("created_at_utc");

                b.Property<string>("DeviceLabel")
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)")
                    .HasColumnName("device_label");

                b.Property<DateTimeOffset>("ExpiresAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("expires_at_utc");

                b.Property<Guid>("FamilyId")
                    .HasColumnType("uuid")
                    .HasColumnName("family_id");

                b.Property<DateTimeOffset?>("RevokedAtUtc")
                    .HasColumnType("timestamp with time zone")
                    .HasColumnName("revoked_at_utc");

                b.Property<string>("TokenHash")
                    .IsRequired()
                    .HasMaxLength(64)
                    .HasColumnType("character varying(64)")
                    .HasColumnName("token_hash");

                b.Property<long>("UserId")
                    .HasColumnType("bigint")
                    .HasColumnName("user_id");

                b.HasKey("Id")
                    .HasName("pk_refresh_tokens");

                b.HasIndex("FamilyId")
                    .HasDatabaseName("ix_refresh_tokens_family_id");

                b.HasIndex("TokenHash")
                    .IsUnique()
                    .HasDatabaseName("ix_refresh_tokens_token_hash");

                b.ToTable("refresh_tokens", (string)null);
            });

        modelBuilder.Entity("Mintmark.Infrastructure.Persistence.SeriesDemandTierRow", b =>
            {
                b.Property<long>("SeriesId")
                    .HasColumnType("bigint")
                    .HasColumnName("series_id");

                b.Property<string>("Tier")
                    .IsRequired()
                    .HasMaxLength(8)
                    .HasColumnType("character varying(8)")
                    .HasColumnName("tier");

                b.HasKey("SeriesId")
                    .HasName("pk_series_demand_tiers");

                b.ToTable("series_demand_tiers", (string)null);
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<long>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<long>", b =>
            {
                b.HasOne("Mintmark.Infrastructure.Persistence.MintmarkUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<long>", b =>
            {
                b.HasOne("Mintmark.Infrastructure.Persistence.MintmarkUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<long>", b =>
            {
                b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<long>", null)
                    .WithMany()
                    .HasForeignKey("RoleId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                b.HasOne("Mintmark.Infrastructure.Persistence.MintmarkUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
            });

        modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<long>", b =>
            {
                b.HasOne("Mintmark.Infrastructure.Persistence.MintmarkUser", null)
                    .WithMany()
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.CoinImage", b =>
            {
                b.HasOne("Mintmark.Domain.Entities.Holding", null)
                    .WithMany()
                    .HasForeignKey("HoldingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_coin_images_holdings_holding_id");
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.CoinType", b =>
            {
                b.HasOne("Mintmark.Domain.Entities.Mint", null)
                    .WithMany()
                    .HasForeignKey("MintId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_coin_types_mints_mint_id");

                b.HasOne("Mintmark.Domain.Entities.Series", null)
                    .WithMany()
                    .HasForeignKey("SeriesId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_coin_types_series_series_id");
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Grading", b =>
            {
                b.HasOne("Mintmark.Domain.Entities.Holding", null)
                    .WithOne()
                    .HasForeignKey("Mintmark.Domain.Entities.Grading", "HoldingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_gradings_holdings_holding_id");
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Holding", b =>
            {
                b.HasOne("Mintmark.Domain.Entities.CoinType", null)
                    .WithMany()
                    .HasForeignKey("CoinTypeId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .HasConstraintName("fk_holdings_coin_types_coin_type_id");
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.HoldingRevision", b =>
            {
                b.HasOne("Mintmark.Domain.Entities.Holding", null)
                    .WithMany("Revisions")
                    .HasForeignKey("HoldingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_holding_revisions_holdings_holding_id");
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Series", b =>
            {
                b.HasOne("Mintmark.Domain.Entities.Mint", null)
                    .WithMany()
                    .HasForeignKey("MintId")
                    .OnDelete(DeleteBehavior.Restrict)
                    .IsRequired()
                    .HasConstraintName("fk_series_mints_mint_id");
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Valuation", b =>
            {
                b.HasOne("Mintmark.Domain.Entities.SpotPrice", null)
                    .WithMany()
                    .HasForeignKey("DerivedFromSpotPriceId")
                    .OnDelete(DeleteBehavior.SetNull)
                    .HasConstraintName("fk_valuations_spot_prices_derived_from_spot_price_id");

                b.HasOne("Mintmark.Domain.Entities.Holding", null)
                    .WithMany()
                    .HasForeignKey("HoldingId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_valuations_holdings_holding_id");
            });

        modelBuilder.Entity("Mintmark.Infrastructure.Persistence.ReferenceImage", b =>
            {
                b.HasOne("Mintmark.Domain.Entities.CoinType", null)
                    .WithMany()
                    .HasForeignKey("CoinTypeId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired()
                    .HasConstraintName("fk_reference_images_coin_types_coin_type_id");
            });

        modelBuilder.Entity("Mintmark.Domain.Entities.Holding", b =>
            {
                b.Navigation("Revisions");
            });
#pragma warning restore 612, 618
    }
}
