<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Quartz" />
    <PackageReference Include="Quartz.Extensions.DependencyInjection" />
    <PackageReference Include="Quartz.Extensions.Hosting" />
    <PackageReference Include="Quartz.Serialization.Json" />
    <PackageReference Include="SixLabors.ImageSharp" />
    <PackageReference Include="NetDevPack.Security.PasswordHasher.Argon2" />
    <PackageReference Include="AWSSDK.S3" />
    <PackageReference Include="Pgvector" />
    <PackageReference Include="Pgvector.EntityFrameworkCore" />
    <ProjectReference Include="..\Mintmark.Application\Mintmark.Application.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
